# -*- coding: utf-8 -*-
"""mistral_agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ohSE_rhcrUVqH7q1VbA9-FROmxjR95h

# 🦜 Agente Pandas con LangChain + Mistral

## ¿Qué es `invoke`?
```
agent.invoke({"input": "tu pregunta"})
    │
    ├─ LangChain construye el prompt automáticamente
    ├─ El agente decide qué herramienta usar (pandas en este caso)
    ├─ Ejecuta código Python sobre el DataFrame
    └─ Devuelve la respuesta en lenguaje natural
```

## ¿Qué es `create_pandas_dataframe_agent`?
Crea un agente que puede ejecutar código pandas sobre tu DataFrame para responder preguntas.
No necesitas escribir ningún query — el agente lo genera solo.

---

## CELDA 1 — Instalación
> Reinicia el runtime cuando termine.
"""

!pip install -q langchain langchain-mistralai langchain-experimental tabulate
print('✅ Listo. Reinicia: Entorno de ejecución → Reiniciar sesión')

"""## CELDA 2 — Imports"""

import pandas as pd
import numpy as np
from google.colab import files, userdata

from langchain_mistralai import ChatMistralAI
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent

print('✅ Imports correctos')
print(f'   pandas {pd.__version__}')

"""## CELDA 3 — Cargar el dataset"""

# Sube tu CSV cuando aparezca el botón
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename, encoding='latin-1')

print(f'✅ Dataset cargado: {filename}')
print(f'   {df.shape[0]:,} filas × {df.shape[1]} columnas')
df.head()

"""## CELDA 4 — Limpieza rápida con pandas"""

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Rellenar NaN
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])
    df[col] = df[col].str.strip().str.upper()

df = df.drop_duplicates()

print(f'✅ Limpieza completa')
print(f'   Filas: {len(df):,}')
print(f'   NaN restantes: {df.isnull().sum().sum()}')
print(f'   Columnas: {df.columns.tolist()}')

"""## CELDA 5 — Crear el LLM con Mistral
> Agrega tu API key en **Secrets** (🔑) con el nombre `MISTRAL_KEY`
"""

MISTRAL_API_KEY = userdata.get('MISTRAL_KEY')

# Inicializar el modelo de Mistral para LangChain
llm = ChatMistralAI(
    model='mistral-large-latest',
    api_key=MISTRAL_API_KEY,
    temperature=0       # 0 = respuestas deterministas, ideal para análisis de datos
)

print('✅ Modelo Mistral listo')
print(f'   Modelo: mistral-large-latest')
print(f'   Temperature: 0')

"""## CELDA 6 — Crear el agente pandas

```
create_pandas_dataframe_agent
    │
    ├─ llm            → el modelo que razona (Mistral)
    ├─ df             → tu DataFrame
    ├─ agent_type     → OPENAI_FUNCTIONS usa function calling
    ├─ verbose        → True muestra el razonamiento paso a paso
    └─ allow_dangerous_code → necesario para ejecutar pandas
```
"""

# Descripción del dataset para que el agente entienda el contexto
PREFIX = """Eres un agente analista de datos de ventas. Tienes acceso a un DataFrame de pandas
llamado `df` con datos de ventas de una empresa. Responde siempre en español.

Columnas del DataFrame:
- ordernumber    : ID único de cada orden
- quantityordered: unidades pedidas
- priceeach      : precio unitario en dólares
- sales          : ingreso total (cantidad × precio)
- orderdate      : fecha de la orden
- status         : estado (Shipped, Cancelled, etc.)
- productline    : línea de producto
- customername   : nombre del cliente
- country        : país del cliente
- dealsize       : tamaño del negocio (Small, Medium, Large)
"""

# Crear el agente
agent = create_pandas_dataframe_agent(
    llm=llm,
    df=df,
    agent_type="openai-tools",
    verbose=True,                  # muestra el razonamiento del agente
    allow_dangerous_code=True,     # permite ejecutar código pandas
    prefix=PREFIX
)

print('✅ Agente pandas creado')

"""## CELDA 7 — Usar `invoke`

`invoke` es el método principal de LangChain para ejecutar el agente.

```python
# Estructura del invoke
resultado = agent.invoke({"input": "tu pregunta"})

# El resultado tiene dos campos:
resultado['input']   # tu pregunta original
resultado['output']  # la respuesta del agente
```

Con `verbose=True` también verás el razonamiento interno:
```
Thought:  → el agente piensa qué hacer
Action:   → decide usar la herramienta pandas
Action Input: → el código pandas que va a ejecutar
Observation: → el resultado del código
Final Answer: → la respuesta en lenguaje natural
```
"""

# ── Ejemplo 1: pregunta simple ────────────────────────────────────
resultado = agent.invoke({"input": "¿Cuántas filas tiene el dataset y cuáles son sus columnas?"})
print('\n══ RESPUESTA ══')
print(resultado['output'])

# ── Ejemplo 2: análisis numérico ──────────────────────────────────
resultado = agent.invoke({"input": "¿Cuál es el total de ventas y el promedio por orden?"})
print('\n══ RESPUESTA ══')
print(resultado['output'])

# ── Ejemplo 3: comparativa ────────────────────────────────────────
resultado = agent.invoke({"input": "Compara las ventas por país y dime cuál lidera"})
print('\n══ RESPUESTA ══')
print(resultado['output'])

"""## CELDA 8 — Tu propio prompt libre
> Cambia la pregunta por lo que necesites analizar.
"""

# ← Escribe aquí tu propia pregunta
mi_pregunta = "¿Cuál es el cliente con más compras y cuánto gastó en total?"

resultado = agent.invoke({"input": mi_pregunta})
print('\n══ RESPUESTA ══')
print(resultado['output'])

"""## CELDA 9 — Chat interactivo con invoke
> Escribe `salir` para terminar.
"""

print('═══════════════════════════════════════')
print('  AGENTE PANDAS — LangChain + Mistral')
print('═══════════════════════════════════════')
print('Escribe cualquier pregunta sobre el dataset.')
print('Escribe "salir" para terminar.\n')

while True:
    entrada = input('Tú: ').strip()
    if not entrada:
        continue
    if entrada.lower() in ['salir', 'exit']:
        print('Agente: ¡Hasta luego!')
        break
    try:
        resultado = agent.invoke({"input": entrada})
        print(f'\nAgente: {resultado["output"]}\n')
        print('─' * 40)
    except Exception as e:
        print(f'\n⚠️ Error: {e}\n')

"""Configurar git"""

!git config --global user.email "pauortec@gmail.com"
!git config --global user.name "pauortec"
!git clone https://github.com/pauortec/IA_CLASES.git
print('✅ Repo clonado')

"""Guardar el notebook RAG actual"""

from google.colab import _message
import json

nb = _message.blocking_request('get_ipynb', request='', timeout_sec=600)
with open('/content/IA_CLASES/rag_langchain_mistral.ipynb', 'w') as f:
    json.dump(nb['ipynb'], f)
print('✅ rag_langchain_mistral.ipynb guardado')

"""Subir notebook del agente pandas"""

import shutil, os

if os.path.exists('/content/langchain_pandas_agent.ipynb'):
    shutil.copy(
        '/content/langchain_pandas_agent.ipynb',
        '/content/IA_CLASES/langchain_pandas_agent.ipynb'
    )
    print('✅ langchain_pandas_agent.ipynb copiado')
else:
    print('⚠️  No se encontró langchain_pandas_agent.ipynb en /content')
    print('   Súbelo manualmente con files.upload() primero')

"""Subir el archivo"""

from google.colab import files
uploaded = files.upload()  # ← selecciona mistral_agente.ipynb desde tu computadora

"""Commit y push"""

# Commented out IPython magic to ensure Python compatibility.
import shutil

shutil.copy('/content/mistral_agente.ipynb', '/content/IA_CLASES/mistral_agente.ipynb')

TOKEN = os.environ.get('GITHUB_TOKEN')

COMMIT_MSG = (
    "feat: Agente Pandas LangChain + Mistral | "
    "C1-instalacion langchain mistralai experimental | "
    "C2-imports pandas numpy ChatMistralAI create_pandas_dataframe_agent | "
    "C3-carga CSV files.upload encoding latin-1 | "
    "C4-limpieza fillna mediana moda drop_duplicates | "
    "C5-ChatMistralAI mistral-large-latest temperature=0 | "
    "C6-create_pandas_dataframe_agent prefix 25 columnas | "
    "C7-ejemplos agent.invoke total ventas promedio cliente top | "
    "C8-prompt libre personalizable | "
    "C9-chat interactivo invoke manejo excepciones"
)

# %cd /content/IA_CLASES
!git add mistral_agente.ipynb
!git commit -m "{COMMIT_MSG}"
!git push https://pauortec:{TOKEN}@github.com/pauortec/IA_CLASES.git main
print('✅ Subido a GitHub')
